In [32]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv('/content/Loan-Approval-Dataset.csv')

In [4]:
print(data.isnull().sum())

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB
None

In [9]:
data=data.dropna()

In [10]:
print(data.isnull().sum())
print(data.info())

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
Index: 480 entries, 1 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            480 non-null    object
 1   Gender             480 non-null    object
 2   Married            480 non-null    object
 3   Dependents         480 non-null    object
 4   Education          480 non-null    object
 5   Self_Employed      480 non-null    object
 6   ApplicantIncome    480 non-null    int64
 7   CoapplicantIncome  480 non-null    float64
 8   LoanAmount         480 non-null    float64
 9   Loan_Amount_Term   480 non-null    float64
 10  Credit_History     480 non-null    float64
 11  Property_Area      480 non-null    object
 12  Loan_Status        480 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 52.5+ KB
None

In [12]:

binary_cols = ['Gender', 'Married', 'Education', 'Self_Employed', 'Loan_Status']
encoder = LabelEncoder()
for col in binary_cols:
    data[col] = encoder.fit_transform(data[col])

data = pd.get_dummies(data, columns=['Dependents', 'Property_Area'], drop_first=True)

In [13]:
data

,Loan_ID,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
1,LP001003,1,1,0,0,4583,1508.0,128.0,360.0,1.0,0,True,False,False,False,False
2,LP001005,1,1,0,1,3000,0.0,66.0,360.0,1.0,1,False,False,False,False,True
3,LP001006,1,1,1,0,2583,2358.0,120.0,360.0,1.0,1,False,False,False,False,True
4,LP001008,1,0,0,0,6000,0.0,141.0,360.0,1.0,1,False,False,False,False,True
5,LP001011,1,1,0,1,5417,4196.0,267.0,360.0,1.0,1,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,0,0,0,0,2900,0.0,71.0,360.0,1.0,1,False,False,False,False,False
610,LP002979,1,1,0,0,4106,0.0,40.0,180.0,1.0,1,False,False,True,False,False
611,LP002983,1,1,0,0,8072,240.0,253.0,360.0,1.0,1,True,False,False,False,True
612,LP002984,1,1,0,0,7583,0.0,187.0,360.0,1.0,1,False,True,False,False,True
613,LP002990,0,0,0,1,4583,0.0,133.0,360.0,0.0,0,False,False,False,True,False

In [15]:
scaler = StandardScaler()
numerical_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History']
data[numerical_cols] = scaler.fit_transform(data[numerical_cols])

In [17]:
X = data.drop(['Loan_ID', 'Loan_Status'], axis=1)
y = data['Loan_Status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Dependents_1,Dependents_2,Dependents_3+,Property_Area_Semiurban,Property_Area_Urban
172,1,1,1,0,-0.325348,-0.604633,-0.792490,-2.487549,0.413197,False,False,True,False,False
288,0,0,0,0,-0.219031,-0.604633,-0.369732,0.275542,0.413197,False,False,False,True,False
607,1,1,1,0,-0.243226,-0.065046,0.152499,0.275542,0.413197,False,True,False,False,False
55,1,1,0,0,-0.469105,-0.158355,-0.593545,0.275542,0.413197,False,True,False,True,False
461,1,1,0,0,0.419573,-0.604633,-0.208089,-2.487549,0.413197,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,1,0,0,0,0.009319,-0.604633,0.289273,0.275542,0.413197,False,False,False,False,True
350,1,1,0,0,0.656754,-0.604633,1.035317,0.275542,0.413197,False,False,False,True,False
445,1,1,0,1,-0.335238,-0.141912,-0.183221,0.275542,0.413197,True,False,False,False,False
558,1,1,0,0,-0.260887,0.416031,0.214669,0.275542,0.413197,False,False,False,True,False
137,1,1,0,1,-0.361729,0.733818,-0.705452,0.275542,0.413197,False,True,False,False,True

In [33]:
model = SVC(probability=True, random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8125

In [34]:
# manually testing the model

import numpy as np
import pandas as pd

manual_data = {
    'Gender': 'Male',
    'Married': 'Yes',
    'Dependents': '1',
    'Education': 'Graduate',
    'Self_Employed': 'No',
    'ApplicantIncome': 5000,
    'CoapplicantIncome': 1500,
    'LoanAmount': 200,
    'Loan_Amount_Term': 360,
    'Credit_History': 1.0,
    'Property_Area': 'Urban'
}

In [35]:
manual_df = pd.DataFrame([manual_data])

In [36]:
manual_df['Gender'] = manual_df['Gender'].map({'Male': 1, 'Female': 0})
manual_df['Married'] = manual_df['Married'].map({'Yes': 1, 'No': 0})
manual_df['Education'] = manual_df['Education'].map({'Graduate': 1, 'Not Graduate': 0})
manual_df['Self_Employed'] = manual_df['Self_Employed'].map({'Yes': 1, 'No': 0})


manual_df = pd.get_dummies(manual_df, columns=['Dependents', 'Property_Area'], drop_first=True)


manual_df = manual_df.reindex(columns=X_train.columns, fill_value=0)


manual_df[numerical_cols] = scaler.transform(manual_df[numerical_cols])

In [38]:
# Make prediction
manual_prediction = model.predict(manual_df)
manual_prediction_proba = model.predict_proba(manual_df)

# Output the result
status = 'Approved' if manual_prediction[0] == 1 else 'Rejected'
print(f"Loan Status: {status}")
print(f"Prediction Probability: {manual_prediction_proba}")

Loan Status: Approved
Prediction Probability: [[0.19834597 0.80165403]]

In [39]:
# [[0.19834597 0.80165403]] =["Approved", "Rejected"]

# 0.19834597: This is the probability of the instance being in class 0 (let's assume "Rejected").
# 0.80165403: This is the probability of the instance being in class 1 (let's assume "Approved").

In [41]:
import joblib


joblib.dump(model, 'LoanPrediction_SVM_Model.pkl')
joblib.dump(model, 'DataEncodingFile_ScalarFile.pkl')

['DataEncodingFile_ScalarFile.pkl']